name: Docker PR Build and Scan

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pull-requests: write
  packages: write

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # - name: Set up Docker Buildx
    #   uses: docker/setup-buildx-action@v2

    # - name: Log in to GitHub Container Registry
    #   uses: docker/login-action@v2
    #   with:
    #     registry: ghcr.io
    #     username: ${{ github.actor }}
    #     password: ${{ secrets.GITHUB_TOKEN }}

    # - name: Build and push Docker image to GHCR
    #   uses: docker/build-push-action@v4
    #   with:
    #     context: .
    #     push: true
    #     tags: |
    #       ghcr.io/${{ github.repository }}/az-pwsh-terraform:${{ github.sha }}
    #       ghcr.io/${{ github.repository }}/az-pwsh-terraform:pr-${{ github.event.pull_request.number }}

    # - name: Scan Docker image with Trivy and generate summary
    #   uses: aquasecurity/trivy-action@0.30.0
    #   with:
    #     image-ref: 'ghcr.io/${{ github.repository }}/az-pwsh-terraform:${{ github.sha }}'
    #     format: 'table'
    #     output: 'trivy-results.txt'
    #     severity: 'CRITICAL,HIGH,MEDIUM'

    # - name: Post Trivy scan results to PR
    #   uses: actions/github-script@v6
    #   if: github.event_name == 'pull_request'
    #   with:
    #     github-token: ${{ secrets.GITHUB_TOKEN }}
    #     script: |
    #       const fs = require('fs');
    #       const bodyFrom = (file) => fs.readFileSync(file, 'utf8');

    #       const full = bodyFrom('trivy-results.txt');
    #       const match = full.match(/Report Summary\n\n([\s\S]*?)\nLegend:/);

    #       const summary = match ? match[1].trim()
    #                             : 'No vulnerability summary found. Please check the full report in the Actions tab.';

    #       const md = [
    #         '## Trivy Security Scan Summary',
    #         '```',
    #         summary,
    #         '```',
    #         '',
    #         '---',
    #         '',
    #         `*For detailed results, see the [workflow run](${github.serverUrl}/${context.repo.owner}/${context.repo.repo}/actions/runs/${process.env.GITHUB_RUN_ID}).*`
    #       ].join('\n');

    #       github.rest.issues.createComment({
    #         ...context.issue,
    #         body: md
    #       });

    # - name: Publish Trivy to action log
    #   run: |
    #     if [[ -s trivy-results.txt ]]; then
    #       {
    #         echo "### Trivy Scan Results"
    #         echo "<details><summary>Click to expand</summary>"
    #         echo ""
    #         echo '```terraform'
    #         cat trivy-results.txt
    #         echo '```'
    #         echo "</details>"
    #       } >> $GITHUB_STEP_SUMMARY
    #     fi

    - name: Clean up old images
      uses: ./.github/actions/ghcr-cleanup-action
      with:
        mode: 'pr'
        include-untagged: 'true'
        token: ${{ github.token }}