name: Docker Tag Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

permissions:
  contents: read
  packages: read

jobs:
  re-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # ──────────────────────────────────────────────────────────────
      # extract version from tag discover the contributing PR
      # ──────────────────────────────────────────────────────────────
      - name: Extract version from tag
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      - name: Get merged-PR number
        id: pr
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          num=$(gh api repos/${{ github.repository }}/commits/${{ github.sha }}/pulls \
                --jq '.[0].number')
          echo "PR_NUMBER=$num" >> $GITHUB_ENV
          echo "REPO_NAME=${GITHUB_REPOSITORY##*/}" >> $GITHUB_ENV

      # ──────────────────────────────────────────────────────────────
      # registry logins
      # ──────────────────────────────────────────────────────────────
      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      # ──────────────────────────────────────────────────────────────
      # pull image built in PR job, retag
      # ──────────────────────────────────────────────────────────────
      - name: Pull image from GHCR
        run: docker pull ghcr.io/${{ github.repository }}:pr-${{ env.PR_NUMBER }}

      - name: Tag and push release version
        run: |
          docker tag ghcr.io/${{ github.repository }}:pr-${{ env.PR_NUMBER }} \
                     ${{ secrets.DOCKER_USERNAME }}/${{ env.REPO_NAME }}:${{ env.VERSION }}
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ env.REPO_NAME }}:${{ env.VERSION }}

