name: Docker Scan and Deploy

on:
  push:
    branches:
      - main

permissions:
  contents: read
  security-events: write
  packages: write

jobs:
  build-scan-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # ──────────────────────────────────────────────────────────────
      # discover the PR that introduced the merge commit
      # ──────────────────────────────────────────────────────────────
      - name: Get merged-PR number
        id: pr
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          num=$(gh api repos/${{ github.repository }}/commits/${{ github.sha }}/pulls \
                --jq '.[0].number')
          echo "PR_NUMBER=$num"       >> $GITHUB_ENV
          echo "REPO_NAME=${GITHUB_REPOSITORY##*/}" >> $GITHUB_ENV

      # ──────────────────────────────────────────────────────────────
      # registry logins
      # ──────────────────────────────────────────────────────────────
      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # ──────────────────────────────────────────────────────────────
      # pull image built in PR job, retag as :latest
      # ──────────────────────────────────────────────────────────────
      - name: Pull image from GHCR
        run: docker pull ghcr.io/${{ github.repository }}:pr-${{ env.PR_NUMBER }}

      - name: Tag image as :latest for Docker Hub
        run: |
          docker tag ghcr.io/${{ github.repository }}:pr-${{ env.PR_NUMBER }} \
                     ${{ secrets.DOCKER_USERNAME }}/${{ env.REPO_NAME }}:latest

      # ──────────────────────────────────────────────────────────────
      # run Trivy again to upload SARIF to GitHub Code Scanning
      # ──────────────────────────────────────────────────────────────
      - name: Scan Docker image with Trivy
        uses: aquasecurity/trivy-action@0.30.0
        with:
          image-ref: '${{ secrets.DOCKER_USERNAME }}/${{ env.REPO_NAME }}:latest'
          format: sarif
          output: results.sarif
          severity: CRITICAL,HIGH

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        if: success() || failure()
        with:
          category: container-security
          sarif_file: results.sarif

      # ──────────────────────────────────────────────────────────────
      # push & cleanup
      # ──────────────────────────────────────────────────────────────
      - name: Push image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/${{ env.REPO_NAME }}:latest

      - name: Remove PR image from GHCR
        uses: ./.github/actions/ghcr-cleanup-action
        with:
          mode: pr
          token: ${{ secrets.GITHUB_TOKEN }}