name: Docker PR Build and Scan

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      run: |
        docker build -t pr-az-pwsh-terraform:latest .

    - name: Scan Docker image with Trivy and generate summary
      uses: aquasecurity/trivy-action@0.30.0
      with:
        image-ref: 'pr-az-pwsh-terraform:latest'
        format: 'table'
        output: 'trivy-results.txt'
        severity: 'CRITICAL,HIGH,MEDIUM'

    - name: Publish Trivy to action log
      run: |
        if [[ -s trivy-results.txt ]]; then
          {
            echo "### Security Output"
            echo "<details><summary>Click to expand</summary>"
            echo ""
            echo '```terraform'
            cat trivy-results.txt
            echo '```'
            echo "</details>"
          } >> $GITHUB_STEP_SUMMARY
        fi

    - name: Post Trivy scan results to PR
      uses: actions/github-script@v6
      if: github.event_name == 'pull_request'
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const fs = require('fs');
          const results = fs.readFileSync('trivy-results.txt', 'utf8');
          
          // Truncate comment if it's too long (GitHub has a limit)
          let comment = '';
          if (results.length > 50000) {
            comment = results.substring(0, 45000) + '\n\n**Note:** The scan results have been truncated due to length. Please check the workflow logs for full results.';
          } else {
            comment = results;
          }
          
          const header = '## Trivy Security Scan Results\n\n';
          const footer = `\n\nThis includes critical, high and medium results, for more details, [view the complete workflow logs](https://github.com/${context.repo.owner}/${context.repo.repo}/actions/runs/${process.env.GITHUB_RUN_ID})`;
          
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: header + '```\n' + comment + '\n```' + footer
          });