name: Docker Scan and Deploy

on:
  push:
    branches:
      - main

permissions:
  contents: read
  security-events: write
  packages: write

jobs:
  build-scan-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Log in to GHCR
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Pull image by digest
      run: |
        docker pull ghcr.io/${{ github.repository }}/az-pwsh-terraform@${{ github.sha }}

    - name: Tag digest as latest
      run: |
        docker tag ghcr.io/${{ github.repository }}/az-pwsh-terraform@${{ github.sha }} \
                  ${{ secrets.DOCKER_USERNAME }}/az-pwsh-terraform:latest

    # the image has been scanned in the PR, we use this to get the SARIF output for the Code Security tab.
    - name: Scan Docker image with Trivy
      uses: aquasecurity/trivy-action@0.30.0
      with:
        image-ref: '${{ secrets.DOCKER_USERNAME }}/az-pwsh-terraform:latest'
        format: 'sarif'
        output: 'results.sarif'
        severity: 'CRITICAL,HIGH'
    
    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@v3
      if: success() || failure()
      with:
        category: container-security
        sarif_file: results.sarif        

    - name: Re-attach SBOM to Docker Hub image
      uses: sigstore/cosign-installer@v3
    - run: |
        COSIGN_EXPERIMENTAL=1 \
        cosign attach sbom \
          --sbom $(cosign download sbom ghcr.io/${{ github.repository }}/az-pwsh-terraform@${{ github.sha }}) \
          ${{ secrets.DOCKER_USERNAME }}/az-pwsh-terraform:latest

    - name: Tag and push to Docker Hub
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/az-pwsh-terraform:latest

    - name: Clean up PR image from GHCR
      uses: ./.github/actions/ghcr-cleanup-action
      with:
        mode: 'specific'
        specific-sha: ${{ github.sha }}
        include-untagged: 'false'
        token: ${{ github.token }}
