name: Docker Tag Release

on:
  push:
    tags:
      - 'v[0-9]+\.[0-9]+\.[0-9]+.*'  # Matches semantic versioning tags like v1.2.3, v1.2.3-beta, etc.

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Extract version from tag
      id: get_version
      run: |
        # Strip the 'v' prefix from the tag
        VERSION=${GITHUB_REF#refs/tags/v}
        echo "VERSION=$VERSION" >> $GITHUB_ENV
        echo "Version extracted: $VERSION"

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Pull image from GHCR
      run: |
        docker pull ghcr.io/${{ github.repository }}/az-pwsh-terraform:${{ github.sha }}

    - name: Tag and push Docker image to Docker Hub
      run: |
        docker tag ghcr.io/${{ github.repository }}/az-pwsh-terraform:${{ github.sha }} ${{ secrets.DOCKER_USERNAME }}/az-pwsh-terraform:${{ env.VERSION }}
        docker tag ghcr.io/${{ github.repository }}/az-pwsh-terraform:${{ github.sha }} ${{ secrets.DOCKER_USERNAME }}/az-pwsh-terraform:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/az-pwsh-terraform:${{ env.VERSION }}
        docker push ${{ secrets.DOCKER_USERNAME }}/az-pwsh-terraform:latest