name: Docker Build, Scan, and Deploy

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-scan-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/az-pwsh-terraform:latest .

    - name: Scan Docker image with Trivy
      run: |
        docker run --rm -v $(pwd):/root/.cache/ aquasec/trivy:latest image \
          --format sarif --output results.sarif ${{ secrets.DOCKER_USERNAME }}/az-pwsh-terraform:latest

    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@v3
      if: success() || failure()
      with:
        category: container-security
        sarif_file: results.sarif

    - name: Push Docker image to Docker Hub
      if: success()
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/az-pwsh-terraform:latest