name: Docker Tag Release

on:
  push:
    tags:
      - 'v[0-9]+\.[0-9]+\.[0-9]+.*'

permissions:
  contents: read
  packages: read        # needed to pull from GHCR

jobs:
  re-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Extract version from tag
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      # GHCR login to pull the digest
      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Pull digest from GHCR
        run: docker pull ghcr.io/${{ github.repository }}/az-pwsh-terraform@${{ github.sha }}

      - name: Tag digest with version
        run: |
          docker tag ghcr.io/${{ github.repository }}/az-pwsh-terraform@${{ github.sha }} \
                     ${{ secrets.DOCKER_USERNAME }}/az-pwsh-terraform:${{ env.VERSION }}

      # optional – copy SBOM across
      - name: Copy SBOM to Docker Hub
        uses: sigstore/cosign-installer@v3
      - run: |
          COSIGN_EXPERIMENTAL=1
          cosign attach sbom \
            --sbom $(cosign download sbom ghcr.io/${{ github.repository }}/az-pwsh-terraform@${{ github.sha }}) \
            ${{ secrets.DOCKER_USERNAME }}/az-pwsh-terraform:${{ env.VERSION }}

      - name: Push version tag to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/az-pwsh-terraform:${{ env.VERSION }}